FROM ckan/ckan-dev:2.10.4

# Install dependencies (for inotifywait and supervisor)
RUN apk update && apk add --no-cache inotify-tools supervisor rsync nodejs npm
RUN npm install -g webpack webpack-cli

# Copy your inotify script into the container
COPY watch_sync.sh /root/watch_sync.sh
COPY global-req.txt /root/requirements.txt
RUN chmod +x /root/watch_sync.sh

# Copy custom initialization scripts
COPY docker-entrypoint.d/* /docker-entrypoint.d/

# Apply any patches needed to CKAN core or any of the built extensions (not the
# runtime mounted ones)
COPY patches ${APP_DIR}/patches

RUN for d in $APP_DIR/patches/*; do \
        if [ -d $d ]; then \
            for f in `ls $d/*.patch | sort -g`; do \
                cd $SRC_DIR/`basename "$d"` && echo "$0: Applying patch $f to $SRC_DIR/`basename $d`"; patch -p1 < "$f" ; \
            done ; \
        fi ; \
    done


