name: CKAN Docker Stack Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install make
      run: sudo apt-get update && sudo apt-get install -y make

    - name: Build and start Docker stack
      run: |
        make create

    - name: Wait for services to be ready
      run: |
        echo "Waiting for CKAN to be ready..."
        timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:5000)" != "200" ]]; do sleep 5; done' || false

    - name: Test CKAN
      run: |
        response=$(curl -sS -o /dev/null -w "%{http_code}" http://localhost:5000)
        if [ $response == "200" ]; then
          echo "CKAN is accessible. Test passed!"
          exit 0
        else
          echo "Failed to access CKAN. HTTP status code: $response"
          exit 1
        fi